name: continuos-deployment
run-name: Deploy do site
on:
    pull_request:
        branches:
            - main
jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        steps:
            - name: Chekout repository
              uses: actions/checkout@v4.2.2
              with:
                fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v6.16.0
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: joaobarsotti/trabalho-desenv-framework-ii:latest
            
            - name: Azure Deploy
              uses: Azure/webapps-deploy@v3.0.1
              with:
                app-name: trabalho-api
                publish-profile: ${{ secrets.PUBLISH_PROFILE }}
                image: joaobarsotti/trabalho-desenv-framework-ii:latest
